//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankId { get; set; }
        public Nullable<int> USD { get; set; }
        public Nullable<int> EUR { get; set; }
        public Nullable<int> CHF { get; set; }
        public Nullable<int> RUB { get; set; }
        public Nullable<int> CZK { get; set; }
        public Nullable<int> GBP { get; set; }
        public Nullable<int> PLN { get; set; }
    }
}
